// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxA-boB53PtXw0uxWlRwBVJkek2yZLhWk',
    appId: '1:703382214228:web:e0bdd5deed4cb74402bfc1',
    messagingSenderId: '703382214228',
    projectId: 'the-classconnect',
    authDomain: 'the-classconnect.firebaseapp.com',
    storageBucket: 'the-classconnect.firebasestorage.app',
    measurementId: 'G-6YRJ7S9ZQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXIpXWbQg1A6cHp0jlyIElCesDYiOHTUc',
    appId: '1:703382214228:android:e1b82d9ec85910f102bfc1',
    messagingSenderId: '703382214228',
    projectId: 'the-classconnect',
    storageBucket: 'the-classconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpZ42Te3AAo1E4VStMQPKCQIZajpXkfU8',
    appId: '1:703382214228:ios:6694ea2bcd66b11802bfc1',
    messagingSenderId: '703382214228',
    projectId: 'the-classconnect',
    storageBucket: 'the-classconnect.firebasestorage.app',
    iosBundleId: 'com.example.classConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpZ42Te3AAo1E4VStMQPKCQIZajpXkfU8',
    appId: '1:703382214228:ios:6694ea2bcd66b11802bfc1',
    messagingSenderId: '703382214228',
    projectId: 'the-classconnect',
    storageBucket: 'the-classconnect.firebasestorage.app',
    iosBundleId: 'com.example.classConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxA-boB53PtXw0uxWlRwBVJkek2yZLhWk',
    appId: '1:703382214228:web:952de7bd925e16a002bfc1',
    messagingSenderId: '703382214228',
    projectId: 'the-classconnect',
    authDomain: 'the-classconnect.firebaseapp.com',
    storageBucket: 'the-classconnect.firebasestorage.app',
    measurementId: 'G-5N5T460B1N',
  );
}
